// flow-typed signature: a0f826152181ccdbe2158434de05e87a
// flow-typed version: <<STUB>>/babel-plugin-rewire_v^1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-rewire'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-rewire' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-rewire/lib/babel-plugin-rewire' {
  declare module.exports: any;
}

declare module 'babel-plugin-rewire/lib/RewireHelpers' {
  declare module.exports: any;
}

declare module 'babel-plugin-rewire/lib/RewireState' {
  declare module.exports: any;
}

declare module 'babel-plugin-rewire/lib/Templates' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-rewire/lib/babel-plugin-rewire.js' {
  declare module.exports: $Exports<
    'babel-plugin-rewire/lib/babel-plugin-rewire'
  >;
}
declare module 'babel-plugin-rewire/lib/RewireHelpers.js' {
  declare module.exports: $Exports<'babel-plugin-rewire/lib/RewireHelpers'>;
}
declare module 'babel-plugin-rewire/lib/RewireState.js' {
  declare module.exports: $Exports<'babel-plugin-rewire/lib/RewireState'>;
}
declare module 'babel-plugin-rewire/lib/Templates.js' {
  declare module.exports: $Exports<'babel-plugin-rewire/lib/Templates'>;
}
