package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReactUI_LintTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReactUI_LintTest")) {
    expectSteps {
        step {
            name = "Install"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "install")
        }
        step {
            name = "Lint"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "workspace @skbkontur/react-ui lint")
        }
        step {
            name = "Test"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "workspace @skbkontur/react-ui test")
        }
        step {
            name = "Smoke test"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "workspace react-ui-smoke-test test")
        }
    }
    steps {
        update<BuildStep>(3) {
            enabled = false
            clearConditions()
        }
    }
}
