package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.SshAgent
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.sshAgent
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReactUI_Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReactUI_Publish")) {
    features {
        val feature1 = find<SshAgent> {
            sshAgent {
                teamcitySshKey = "GitHub"
            }
        }
        feature1.apply {
            teamcitySshKey = "GitHub_ skbkontur-bot"
        }
    }
}
