package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.DotnetTestStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dotnetTest
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SeleniumTesting_Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SeleniumTesting_Test")) {
    expectSteps {
        step {
            name = "Install"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "install")
        }
        step {
            name = "Build"
            type = "jonnyzzz.yarn"
            param("yarn_commands", """
                workspace @skbkontur/react-ui build
                workspace react-ui-testing build
            """.trimIndent())
        }
        script {
            name = "Start"
            scriptContent = """
                start /b yarn workspace react-ui-testing start
                ping 127.0.0.1 -n 11
            """.trimIndent()
        }
        dotnetTest {
            name = "Test"
            projects = "packages/react-ui-testing/Tests/Tests.csproj"
            framework = "netcoreapp2.1"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
    }
    steps {
        update<DotnetTestStep>(3) {
            clearConditions()
            framework = "netcoreapp3.1"
        }
    }
}
