package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.DotnetMsBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MSBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dotnetMsBuild
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.msBuild
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.nuGetInstaller
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.nunit
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Validations_LintTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Validations_LintTest")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    expectSteps {
        step {
            name = "Install"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "install")
        }
        step {
            name = "Lint"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "workspace react-ui-validations lint")
        }
        step {
            name = "Run unit tests"
            type = "jonnyzzz.yarn"
            param("yarn_commands", "workspace react-ui-validations test")
        }
        script {
            name = "Start Storybook"
            scriptContent = """
                start /b yarn workspace react-ui-validations storybook
                ping 127.0.0.1 -n 60
            """.trimIndent()
        }
        nuGetInstaller {
            name = "NuGet Restore"
            toolPath = "%teamcity.tool.NuGet.CommandLine.4.9.3%"
            projects = "packages/react-ui-validations/selenium-tests/SeleniumTests.sln"
        }
        msBuild {
            name = "Build tests"
            path = "packages/react-ui-validations/selenium-tests/SeleniumTests.sln"
            version = MSBuildStep.MSBuildVersion.V15_0
            toolsVersion = MSBuildStep.MSBuildToolsVersion.V15_0
        }
        nunit {
            name = "Run tests"
            nunitPath = "%teamcity.tool.NUnit.Console.DEFAULT%"
            includeTests = """packages\react-ui-validations\selenium-tests\ValidationTests\bin\Debug\ValidationTests.dll"""
        }
    }
    steps {
        insert(5) {
            dotnetMsBuild {
                name = "Build tests"
                projects = "packages/react-ui-validations/selenium-tests/SeleniumTests.sln"
                version = DotnetMsBuildStep.MSBuildVersion.CrossPlatform
                param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
            }
        }
        items.removeAt(6)
    }
}
