package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Validations_ScreenshotTests'
in the project with id = 'Validations', and delete the patch script.
*/
create(RelativeId("Validations"), BuildType({
    id("Validations_ScreenshotTests")
    name = "Screenshot tests"

    vcs {
        root(DslContext.settingsRoot)
    }
    
    disableSettings("VCS_TRIGGER")
}))

