package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Validations_ScreenshotTests'
in the project with id = 'Validations', and delete the patch script.
*/
create(RelativeId("Validations"), BuildType({
    id("Validations_ScreenshotTests")
    name = "Screenshot tests"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        nodeJS {
            id = "RUNNER_10859"
            shellScript = "npm install"
        }
    }
}))

