// flow-typed signature: 0e28a1a385393b7c4e959cc7dbb9679c
// flow-typed version: <<STUB>>/@types/react_v^16.0.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
