// flow-typed signature: c13bb35715c85096ae7d2fe5bc12a1d6
// flow-typed version: <<STUB>>/@kadira/storybook-addon-knobs_v^1.7.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-addon-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-addon-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-addon-knobs/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/PropField' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/PropForm' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Array' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Color' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Date/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Date/styles' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Number' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Object' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Select' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/types/Text' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/components/WrapStory' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/KnobManager' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/KnobStore' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/dist/register' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/example/stories/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addon-knobs/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-addon-knobs/dist/components/Panel.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/Panel'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/PropField.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/PropField'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/PropForm.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/PropForm'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Array.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Array'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Boolean.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Boolean'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Color.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Color'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Date/index.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Date/index'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Date/styles.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Date/styles'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/index.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/index'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Number.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Number'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Object.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Object'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Select.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Select'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/types/Text.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/types/Text'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/components/WrapStory.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/components/WrapStory'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-knobs/dist/index'>;
}
declare module '@kadira/storybook-addon-knobs/dist/KnobManager.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/KnobManager'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/KnobStore.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/KnobStore'
  >;
}
declare module '@kadira/storybook-addon-knobs/dist/register.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/dist/register'
  >;
}
declare module '@kadira/storybook-addon-knobs/example/stories/index.js' {
  declare module.exports: $Exports<
    '@kadira/storybook-addon-knobs/example/stories/index'
  >;
}
declare module '@kadira/storybook-addon-knobs/register.js' {
  declare module.exports: $Exports<'@kadira/storybook-addon-knobs/register'>;
}
