// flow-typed signature: beb4d6c546e1e70536c8738b68b52593
// flow-typed version: <<STUB>>/add-event-listener_v0.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'add-event-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'add-event-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'add-event-listener/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'add-event-listener/index' {
  declare module.exports: $Exports<'add-event-listener'>;
}
declare module 'add-event-listener/index.js' {
  declare module.exports: $Exports<'add-event-listener'>;
}
declare module 'add-event-listener/test.js' {
  declare module.exports: $Exports<'add-event-listener/test'>;
}
