// flow-typed signature: 6b80436b2c74a23a3e99ced1f1a0f166
// flow-typed version: <<STUB>>/eslint-plugin-sort-class-members_v^1.1.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-sort-class-members'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-sort-class-members' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-sort-class-members/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort-class-members/dist/rules/schema' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sort-class-members/dist/rules/sort-class-members' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-sort-class-members/dist/index.js' {
  declare module.exports: $Exports<
    'eslint-plugin-sort-class-members/dist/index'
  >;
}
declare module 'eslint-plugin-sort-class-members/dist/rules/schema.js' {
  declare module.exports: $Exports<
    'eslint-plugin-sort-class-members/dist/rules/schema'
  >;
}
declare module 'eslint-plugin-sort-class-members/dist/rules/sort-class-members.js' {
  declare module.exports: $Exports<
    'eslint-plugin-sort-class-members/dist/rules/sort-class-members'
  >;
}
