// flow-typed signature: 30846992f30231e2edffbaf1a0f2a0a6
// flow-typed version: <<STUB>>/gemini-sauce_v^1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gemini-sauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gemini-sauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gemini-sauce/lib/plugin' {
  declare module.exports: any;
}

declare module 'gemini-sauce/lib/sauce' {
  declare module.exports: any;
}

declare module 'gemini-sauce/test/plugin' {
  declare module.exports: any;
}

declare module 'gemini-sauce/test/sauce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gemini-sauce/lib/plugin.js' {
  declare module.exports: $Exports<'gemini-sauce/lib/plugin'>;
}
declare module 'gemini-sauce/lib/sauce.js' {
  declare module.exports: $Exports<'gemini-sauce/lib/sauce'>;
}
declare module 'gemini-sauce/test/plugin.js' {
  declare module.exports: $Exports<'gemini-sauce/test/plugin'>;
}
declare module 'gemini-sauce/test/sauce.js' {
  declare module.exports: $Exports<'gemini-sauce/test/sauce'>;
}
