// flow-typed signature: e17b7fa85045cd98086f6f40486a3d85
// flow-typed version: <<STUB>>/less-loader_v3.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-loader' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'less-loader/lib/loader' {
  declare module.exports: any;
}
declare module 'less-loader/lib/stringify.loader' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'less-loader/lib/loader.js' {
  declare module.exports: $Exports<'less-loader/lib/loader'>;
}
declare module 'less-loader/lib/stringify.loader.js' {
  declare module.exports: $Exports<'less-loader/lib/stringify.loader'>;
}
