// flow-typed signature: a4e342c74ac61bb022275c145c53bbc6
// flow-typed version: <<STUB>>/output-file-sync_v^2.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'output-file-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'output-file-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'output-file-sync/index' {
  declare module.exports: $Exports<'output-file-sync'>;
}
declare module 'output-file-sync/index.js' {
  declare module.exports: $Exports<'output-file-sync'>;
}
