// flow-typed signature: 18fc5a5e56c67b823333eb0c5450d37a
// flow-typed version: <<STUB>>/react-docgen-typescript_v^1.2.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-docgen-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-docgen-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-docgen-typescript/lib/__tests__/__sourceMapInit' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/buildFilter' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/data/ExtendsExternalPropsComponentParentProps' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/data/ExternalPropsComponentProps' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/data/transformAST_external' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/data/transformAST_hoc' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/manualTest' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/parser' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/__tests__/testUtils' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/buildFilter' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/index' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/parser' {
  declare module.exports: any;
}

declare module 'react-docgen-typescript/lib/propTypesParser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-docgen-typescript/lib/__tests__/__sourceMapInit.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/__sourceMapInit'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/buildFilter.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/buildFilter'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/data/ExtendsExternalPropsComponentParentProps.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/data/ExtendsExternalPropsComponentParentProps'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/data/ExternalPropsComponentProps.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/data/ExternalPropsComponentProps'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/data/transformAST_external.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/data/transformAST_external'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/data/transformAST_hoc.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/data/transformAST_hoc'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/manualTest.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/manualTest'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/parser.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/parser'
  >;
}
declare module 'react-docgen-typescript/lib/__tests__/testUtils.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/__tests__/testUtils'
  >;
}
declare module 'react-docgen-typescript/lib/buildFilter.js' {
  declare module.exports: $Exports<'react-docgen-typescript/lib/buildFilter'>;
}
declare module 'react-docgen-typescript/lib/index.js' {
  declare module.exports: $Exports<'react-docgen-typescript/lib/index'>;
}
declare module 'react-docgen-typescript/lib/parser.js' {
  declare module.exports: $Exports<'react-docgen-typescript/lib/parser'>;
}
declare module 'react-docgen-typescript/lib/propTypesParser.js' {
  declare module.exports: $Exports<
    'react-docgen-typescript/lib/propTypesParser'
  >;
}
