// flow-typed signature: 341a4a3356f63244d3b3d6c388d7da3d
// flow-typed version: <<STUB>>/react-input-mask_v^0.8.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-mask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-mask' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-mask/build/InputElement' {
  declare module.exports: any;
}

declare module 'react-input-mask/InputElement' {
  declare module.exports: any;
}

declare module 'react-input-mask/karma.conf' {
  declare module.exports: any;
}

declare module 'react-input-mask/tests_prerender/prerender' {
  declare module.exports: any;
}

declare module 'react-input-mask/tests/input-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-mask/build/InputElement.js' {
  declare module.exports: $Exports<'react-input-mask/build/InputElement'>;
}
declare module 'react-input-mask/InputElement.js' {
  declare module.exports: $Exports<'react-input-mask/InputElement'>;
}
declare module 'react-input-mask/karma.conf.js' {
  declare module.exports: $Exports<'react-input-mask/karma.conf'>;
}
declare module 'react-input-mask/tests_prerender/prerender.js' {
  declare module.exports: $Exports<
    'react-input-mask/tests_prerender/prerender'
  >;
}
declare module 'react-input-mask/tests/input-test.js' {
  declare module.exports: $Exports<'react-input-mask/tests/input-test'>;
}
