import type { TokensBase } from './types/tokens-base.js';

export const getColorsDefaultTokens = (base: TokensBase) => ({
  light: {
    textAccentHeavy: base.accent?.palette?.vivid[52] || base.blackAlpha[88],
    textAccentHeavyHover: base.accent?.palette?.vivid[60] || base.blackAlpha[96],
    textAccentHeavyPressed: base.accent?.palette?.dim[48] || base.blackAlpha[96],
    textErrorHeavy: base.customizable.red.vivid[52],
    textErrorHeavyHover: base.customizable.red.vivid[60],
    textErrorHeavyPressed: base.customizable.red.dim[48],
    textInvertedAccentHeavy: base.accent?.palette?.vivid[72] || base.whiteAlpha[96],
    textInvertedAccentHeavyHover: base.accent?.palette?.vivid[80] || base.gray[100],
    textInvertedAccentHeavyPressed: base.accent?.palette?.dim[64] || base.gray[100],
    textInvertedErrorHeavy: base.customizable.red.vivid[68],
    textInvertedErrorHeavyHover: base.customizable.red.vivid[72],
    textInvertedErrorHeavyPressed: base.customizable.red.dim[64],
    textInvertedNeutralFaint: base.whiteAlpha[40],
    textInvertedNeutralHeavy: base.whiteAlpha[96],
    textInvertedNeutralPale: base.whiteAlpha[48],
    textInvertedNeutralSoft: base.whiteAlpha[64],
    textInvertedSuccessHeavy: base.customizable.green.vivid[72],
    textInvertedSuccessHeavyHover: base.customizable.green.vivid[80],
    textInvertedSuccessHeavyPressed: base.customizable.green.dim[64],
    textInvertedWarningHeavy: base.warning.vivid[80],
    textInvertedWarningHeavyHover: base.warning.vivid[84],
    textInvertedWarningHeavyPressed: base.warning.dim[72],
    textLogo: base.brand.logo.light,
    textNeutralFaint: base.blackAlpha[32],
    textNeutralHeavy: base.blackAlpha[88],
    textNeutralPale: base.blackAlpha[40],
    textNeutralSoft: base.blackAlpha[56],
    textSuccessHeavy: base.customizable.green.vivid[52],
    textSuccessHeavyHover: base.customizable.green.vivid[60],
    textSuccessHeavyPressed: base.customizable.green.dim[48],
    textWarningHeavy: base.warning.vivid[64],
    textWarningHeavyHover: base.warning.vivid[72],
    textWarningHeavyPressed: base.warning.dim[60],
    textConstFaintBlack: base.blackAlpha[32],
    textConstFaintWhite: base.whiteAlpha[40],
    textConstHeavyBlack: base.blackAlpha[88],
    textConstHeavyWhite: base.whiteAlpha[96],
    textConstPaleBlack: base.blackAlpha[40],
    textConstPaleWhite: base.whiteAlpha[48],
    textConstSoftBlack: base.blackAlpha[56],
    textConstSoftWhite: base.whiteAlpha[64],
    textOnAccentBoldFaint: base.onAccent?.[40] || base.whiteAlpha[40],
    textOnAccentBoldHeavy: base.onAccent?.[96] || base.whiteAlpha[96],
    textOnAccentBoldPale: base.onAccent?.[48] || base.whiteAlpha[48],
    textOnAccentBoldSoft: base.onAccent?.[64] || base.whiteAlpha[64],
    textOnBrandOriginalFaint: base.onBrand[40],
    textOnBrandOriginalHeavy: base.onBrand[96],
    textOnBrandOriginalPale: base.onBrand[48],
    textOnBrandOriginalSoft: base.onBrand[64],
    shapeBoldAccent: base.accent?.original.light || base.gray[36],
    shapeBoldAccentHover: base.accent?.interactions.hover.light || base.gray[28],
    shapeBoldAccentPressed: base.accent?.interactions.pressed.light || base.gray[20],
    shapeBoldBrandOriginal: base.brand.original,
    shapeBoldBrandOriginalHover: base.brand.interactions.hover.light,
    shapeBoldBrandOriginalPressed: base.brand.interactions.pressed.light,
    shapeBoldError: base.customizable.red.vivid[64],
    shapeBoldErrorHover: base.customizable.red.vivid[60],
    shapeBoldErrorPressed: base.customizable.red.normal[56],
    shapeBoldNeutral: base.gray[44],
    shapeBoldNeutralHover: base.gray[36],
    shapeBoldNeutralPressed: base.blackAlpha[56],
    shapeBoldSuccess: base.customizable.green.vivid[64],
    shapeBoldSuccessHover: base.customizable.green.vivid[60],
    shapeBoldSuccessPressed: base.customizable.green.normal[56],
    shapeBoldWarning: base.warning.vivid[84],
    shapeBoldWarningHover: base.warning.vivid[80],
    shapeBoldWarningPressed: base.warning.normal[76],
    shapeFaintAccent: base.accent?.palette?.normal[96] || base.blackAlpha[12],
    shapeFaintAccentHover: base.accent?.palette?.normal[92] || base.blackAlpha[16],
    shapeFaintAccentPressed: base.accent?.palette?.dim[88] || base.blackAlpha[24],
    shapeFaintBrand: base.brand.palette?.vivid[96],
    shapeFaintBrandHover: base.brand.palette?.normal[92],
    shapeFaintBrandPressed: base.brand.palette?.dim[92],
    shapeFaintError: base.customizable.red.vivid[96],
    shapeFaintErrorHover: base.customizable.red.normal[92],
    shapeFaintErrorPressed: base.customizable.red.dim[92],
    shapeFaintNeutralAlpha: base.blackAlpha[6],
    shapeFaintNeutralAlphaHover: base.blackAlpha[12],
    shapeFaintNeutralAlphaPressed: base.blackAlpha[16],
    shapeFaintSuccess: base.customizable.green.normal[96],
    shapeFaintSuccessHover: base.customizable.green.normal[92],
    shapeFaintSuccessPressed: base.customizable.green.dim[92],
    shapeFaintWarning: base.warning.vivid[96],
    shapeFaintWarningHover: base.warning.normal[92],
    shapeFaintWarningPressed: base.warning.dim[92],
    shapeHeavyError: base.customizable.red.normal[36],
    shapeHeavyNeutral: base.gray[28],
    shapeHeavySuccess: base.customizable.green.normal[36],
    shapeHeavyWarning: base.warning.vivid[36],
    shapeOtherAccentBoldDisabled: base.blackAlpha[32],
    shapeOtherBacklessHover: base.blackAlpha[6],
    shapeOtherBacklessPressed: base.blackAlpha[16],
    shapeOtherBase: base.gray[100],
    shapeOtherBaseHover: base.gray[96],
    shapeOtherBasePressed: base.gray[92],
    shapeOtherDisabled: base.blackAlpha[6],
    shapeOtherField: base.gray[100],
    shapeOtherFieldHover: base.gray[96],
    shapeOtherFieldPressed: base.gray[92],
    shapeOtherLow: base.blackAlpha[6],
    shapeOtherLowHover: base.blackAlpha[8],
    shapeOtherLowPressed: base.blackAlpha[12],
    shapeOtherNeutralFaintSolid: base.gray[96],
    shapeOtherNeutralFaintSolidHover: base.gray[92],
    shapeOtherNeutralFaintSolidPressed: base.gray[88],
    shapeOtherNeutralPaleSolid: base.gray[92],
    shapeOtherNeutralPaleSolidHover: base.gray[88],
    shapeOtherNeutralPaleSolidPressed: base.gray[84],
    shapeOtherNeutralSoftSolid: base.gray[88],
    shapeOtherNeutralSoftSolidHover: base.gray[80],
    shapeOtherNeutralSoftSolidPressed: base.gray[76],
    shapePaleAccent: base.accent?.palette?.vivid[92] || base.blackAlpha[16],
    shapePaleAccentHover: base.accent?.palette?.normal[88] || base.blackAlpha[24],
    shapePaleAccentPressed: base.accent?.palette?.dim[84] || base.blackAlpha[32],
    shapePaleBrand: base.brand.palette?.vivid[92],
    shapePaleBrandHover: base.brand.palette?.normal[88],
    shapePaleBrandPressed: base.brand.palette?.dim[88],
    shapePaleError: base.customizable.red.vivid[92],
    shapePaleErrorHover: base.customizable.red.normal[88],
    shapePaleErrorPressed: base.customizable.red.dim[88],
    shapePaleNeutralAlpha: base.blackAlpha[12],
    shapePaleNeutralAlphaHover: base.blackAlpha[16],
    shapePaleNeutralAlphaPressed: base.blackAlpha[24],
    shapePaleSuccess: base.customizable.green.normal[92],
    shapePaleSuccessHover: base.customizable.green.normal[88],
    shapePaleSuccessPressed: base.customizable.green.dim[88],
    shapePaleWarning: base.warning.vivid[92],
    shapePaleWarningHover: base.warning.normal[88],
    shapePaleWarningPressed: base.warning.dim[88],
    shapeSoftAccent: base.accent?.palette?.normal[80] || base.blackAlpha[32],
    shapeSoftAccentHover: base.accent?.palette?.normal[76] || base.blackAlpha[40],
    shapeSoftAccentPressed: base.accent?.palette?.dim[72] || base.blackAlpha[48],
    shapeSoftBrand: base.brand.palette?.normal[80],
    shapeSoftBrandHover: base.brand.palette?.normal[76],
    shapeSoftBrandPressed: base.brand.palette?.dim[72],
    shapeSoftError: base.customizable.red.normal[80],
    shapeSoftErrorHover: base.customizable.red.normal[76],
    shapeSoftErrorPressed: base.customizable.red.dim[72],
    shapeSoftNeutralAlpha: base.blackAlpha[16],
    shapeSoftNeutralAlphaHover: base.blackAlpha[24],
    shapeSoftNeutralAlphaPressed: base.blackAlpha[32],
    shapeSoftSuccess: base.customizable.green.normal[80],
    shapeSoftSuccessHover: base.customizable.green.normal[76],
    shapeSoftSuccessPressed: base.customizable.green.dim[72],
    shapeSoftWarning: base.warning.vivid[88],
    shapeSoftWarningHover: base.warning.normal[84],
    shapeSoftWarningPressed: base.warning.dim[80],
    shapeInvertedBacklessHover: base.whiteAlpha[6],
    shapeInvertedBacklessPressed: base.whiteAlpha[4],
    shapeInvertedDisabled: base.whiteAlpha[6],
    shapeInvertedNeutralFaintAlpha: base.whiteAlpha[6],
    shapeInvertedNeutralFaintAlphaHover: base.whiteAlpha[8],
    shapeInvertedNeutralFaintAlphaPressed: base.whiteAlpha[4],
    shapeInvertedNeutralHeavy: base.gray[100],
    shapeInvertedNeutralHeavyHover: base.whiteAlpha[88],
    shapeInvertedNeutralHeavyPressed: base.whiteAlpha[72],
    shapeInvertedNeutralPaleAlpha: base.whiteAlpha[12],
    shapeInvertedNeutralPaleAlphaHover: base.whiteAlpha[16],
    shapeInvertedNeutralPaleAlphaPressed: base.whiteAlpha[6],
    shapeInvertedNeutralSoftAlpha: base.whiteAlpha[16],
    shapeInvertedNeutralSoftAlphaHover: base.whiteAlpha[24],
    shapeInvertedNeutralSoftAlphaPressed: base.whiteAlpha[8],
    shapeConstBacklessBlackHover: base.blackAlpha[12],
    shapeConstBacklessBlackPressed: base.blackAlpha[16],
    shapeConstBacklessWhiteHover: base.whiteAlpha[12],
    shapeConstBacklessWhitePressed: base.whiteAlpha[6],
    shapeConstDisabledBlack: base.blackAlpha[6],
    shapeConstDisabledWhite: base.whiteAlpha[6],
    shapeConstFaintBlack: base.blackAlpha[12],
    shapeConstFaintBlackHover: base.blackAlpha[16],
    shapeConstFaintBlackPressed: base.blackAlpha[24],
    shapeConstFaintWhite: base.whiteAlpha[12],
    shapeConstFaintWhiteHover: base.whiteAlpha[16],
    shapeConstFaintWhitePressed: base.whiteAlpha[8],
    shapeConstHeavyBlack: base.blackAlpha[80],
    shapeConstHeavyBlackHover: base.blackAlpha[88],
    shapeConstHeavyBlackPressed: base.blackAlpha[64],
    shapeConstHeavyWhite: base.whiteAlpha[96],
    shapeConstHeavyWhiteHover: base.gray[100],
    shapeConstHeavyWhitePressed: base.whiteAlpha[64],
    shapeConstPaleBlack: base.blackAlpha[16],
    shapeConstPaleBlackHover: base.blackAlpha[24],
    shapeConstPaleBlackPressed: base.blackAlpha[32],
    shapeConstPaleWhite: base.whiteAlpha[16],
    shapeConstPaleWhiteHover: base.whiteAlpha[24],
    shapeConstPaleWhitePressed: base.whiteAlpha[12],
    shapeConstPromo: base.brand.promo,
    shapeConstSoftBlack: base.blackAlpha[24],
    shapeConstSoftBlackHover: base.blackAlpha[32],
    shapeConstSoftBlackPressed: base.blackAlpha[40],
    shapeConstSoftWhite: base.whiteAlpha[24],
    shapeConstSoftWhiteHover: base.whiteAlpha[32],
    shapeConstSoftWhitePressed: base.whiteAlpha[24],
    lineAccentBold: base.accent?.original.light || base.gray[40],
    lineAccentBoldHover: base.accent?.interactions.hover.light || base.gray[20],
    lineAccentBoldPressed: base.accent?.interactions.pressed.light || base.blackAlpha[64],
    lineAccentPale: base.accent?.palette?.normal[88] || base.blackAlpha[24],
    lineAccentPaleHover: base.accent?.palette?.normal[84] || base.blackAlpha[32],
    lineAccentPalePressed: base.accent?.palette?.dim[80] || base.blackAlpha[40],
    lineAccentSoft: base.accent?.palette?.dim[76] || base.blackAlpha[48],
    lineAccentSoftHover: base.accent?.palette?.vivid[60] || base.blackAlpha[96],
    lineAccentSoftPressed: base.accent?.palette?.dim[48] || base.blackAlpha[96],
    lineBrandOriginal: base.brand.original,
    lineErrorBold: base.customizable.red.vivid[56],
    lineErrorBoldHover: base.customizable.red.vivid[64],
    lineErrorBoldPressed: base.customizable.red.dim[52],
    lineNeutralFaint: base.blackAlpha[8],
    lineNeutralPale: base.blackAlpha[16],
    lineNeutralPaleHover: base.blackAlpha[24],
    lineNeutralPalePressed: base.blackAlpha[40],
    lineOnAccentBoldFaint: base.onAccent?.[12] || base.whiteAlpha[12],
    lineOnAccentBoldPale: base.onAccent?.[24] || base.whiteAlpha[24],
    lineOnBrandOriginalFaint: base.onBrand[12],
    lineOnBrandOriginalPale: base.onBrand[24],
    lineSuccessBold: base.customizable.green.vivid[56],
    lineSuccessBoldHover: base.customizable.green.vivid[68],
    lineSuccessBoldPressed: base.customizable.green.dim[56],
    lineWarningBold: base.warning.vivid[80],
    lineWarningBoldHover: base.warning.vivid[72],
    lineWarningBoldPressed: base.warning.dim[68],
    lineInvertedAccentBold: base.accent?.original.dark || base.gray[88],
    lineInvertedAccentBoldHover: base.accent?.interactions.hover.dark || base.gray[100],
    lineInvertedAccentBoldPressed: base.accent?.interactions.pressed.dark || base.whiteAlpha[64],
    lineInvertedAccentPale: base.accent?.palette?.dim[44] || base.whiteAlpha[24],
    lineInvertedAccentPaleHover: base.accent?.palette?.dim[48] || base.whiteAlpha[32],
    lineInvertedAccentPalePressed: base.accent?.palette?.dim[40] || base.whiteAlpha[16],
    lineInvertedAccentSoft: base.accent?.palette?.dim[48] || base.whiteAlpha[48],
    lineInvertedAccentSoftHover: base.accent?.palette?.vivid[80] || base.gray[100],
    lineInvertedAccentSoftPressed: base.accent?.palette?.normal[64] || base.gray[100],
    lineInvertedErrorBold: base.customizable.red.vivid[60],
    lineInvertedErrorBoldHover: base.customizable.red.vivid[68],
    lineInvertedErrorBoldPressed: base.customizable.red.dim[56],
    lineInvertedNeutralFaint: base.whiteAlpha[8],
    lineInvertedNeutralPale: base.whiteAlpha[16],
    lineInvertedNeutralPaleHover: base.whiteAlpha[24],
    lineInvertedNeutralPalePressed: base.whiteAlpha[12],
    lineInvertedSuccessBold: base.customizable.green.vivid[60],
    lineInvertedSuccessBoldHover: base.customizable.green.vivid[68],
    lineInvertedSuccessBoldPressed: base.customizable.green.dim[56],
    lineInvertedWarningBold: base.warning.vivid[80],
    lineInvertedWarningBoldHover: base.warning.vivid[84],
    lineInvertedWarningBoldPressed: base.warning.dim[72],
    lineConstFaintBlack: base.blackAlpha[12],
    lineConstFaintWhite: base.whiteAlpha[12],
    lineConstPaleBlack: base.blackAlpha[24],
    lineConstPaleBlackHover: base.blackAlpha[32],
    lineConstPaleBlackPressed: base.blackAlpha[16],
    lineConstPaleWhite: base.whiteAlpha[24],
    lineConstPaleWhiteHover: base.whiteAlpha[32],
    lineConstPaleWhitePressed: base.whiteAlpha[16],
    surfaceBase: base.gray[100],
    surfaceHigh: base.gray[100],
    surfaceLow: base.gray[96],
    surfaceModalBackdrop: base.blackAlpha[24],
    illustrationBlack: base.gray[16],
    illustrationBrand: base.brand.original,
    illustrationComplement: base.brand.promo,
    illustrationInvertedNeutral: base.gray[100],
    illustrationNeutral: base.gray[0],
    illustrationOnBrand: base.onBrand[100],
    illustrationOnComplement: base.gray[100],
    illustrationPromo: base.brand.promo,
    illustrationSymbol: base.brand.palette?.normal[80],
    illustrationWhite: base.gray[100],
    customizableBoldBlack: base.gray[52],
    customizableBoldBlue: base.customizable.blue.vivid[68],
    customizableBoldBlueDeep: base.customizable.blueDeep.vivid[64],
    customizableBoldGray: base.gray[72],
    customizableBoldGreen: base.customizable.green.vivid[68],
    customizableBoldMint: base.customizable.mint.vivid[72],
    customizableBoldOrange: base.customizable.orange.vivid[68],
    customizableBoldPurple: base.customizable.purple.vivid[68],
    customizableBoldRed: base.customizable.red.vivid[68],
    customizableBoldViolet: base.customizable.violet.vivid[68],
    customizableBoldYellow: base.customizable.yellow.vivid[80],
    customizableFaintBlack: base.gray[92],
    customizableFaintBlue: base.customizable.blue.vivid[96],
    customizableFaintBlueDeep: base.customizable.blueDeep.vivid[96],
    customizableFaintGray: base.gray[96],
    customizableFaintGreen: base.customizable.green.normal[96],
    customizableFaintMint: base.customizable.mint.normal[96],
    customizableFaintOrange: base.customizable.orange.vivid[96],
    customizableFaintPurple: base.customizable.purple.vivid[96],
    customizableFaintRed: base.customizable.red.vivid[96],
    customizableFaintViolet: base.customizable.violet.vivid[96],
    customizableFaintYellow: base.customizable.yellow.vivid[96],
    customizableHeavyBlack: base.gray[36],
    customizableHeavyBlue: base.customizable.blue.vivid[48],
    customizableHeavyBlueDeep: base.customizable.blueDeep.vivid[48],
    customizableHeavyGray: base.gray[56],
    customizableHeavyGreen: base.customizable.green.vivid[48],
    customizableHeavyMint: base.customizable.mint.vivid[52],
    customizableHeavyOrange: base.customizable.orange.vivid[48],
    customizableHeavyPurple: base.customizable.purple.vivid[48],
    customizableHeavyRed: base.customizable.red.vivid[52],
    customizableHeavyViolet: base.customizable.violet.vivid[48],
    customizableHeavyYellow: base.customizable.yellow.vivid[56],
    customizablePaleBlack: base.gray[88],
    customizablePaleBlue: base.customizable.blue.vivid[92],
    customizablePaleBlueDeep: base.customizable.blueDeep.vivid[92],
    customizablePaleGray: base.gray[92],
    customizablePaleGreen: base.customizable.green.normal[92],
    customizablePaleMint: base.customizable.mint.normal[92],
    customizablePaleOrange: base.customizable.orange.vivid[92],
    customizablePalePurple: base.customizable.purple.vivid[92],
    customizablePaleRed: base.customizable.red.vivid[92],
    customizablePaleViolet: base.customizable.violet.vivid[92],
    customizablePaleYellow: base.customizable.yellow.vivid[92],
    customizableSoftBlack: base.gray[76],
    customizableSoftBlue: base.customizable.blue.vivid[80],
    customizableSoftBlueDeep: base.customizable.blueDeep.vivid[80],
    customizableSoftGray: base.gray[88],
    customizableSoftGreen: base.customizable.green.normal[80],
    customizableSoftMint: base.customizable.mint.normal[84],
    customizableSoftOrange: base.customizable.orange.vivid[80],
    customizableSoftPurple: base.customizable.purple.vivid[80],
    customizableSoftRed: base.customizable.red.vivid[80],
    customizableSoftViolet: base.customizable.violet.vivid[80],
    customizableSoftYellow: base.customizable.yellow.vivid[88],
  },
  dark: {
    textAccentHeavy: base.accent?.palette?.vivid[72] || base.whiteAlpha[96],
    textAccentHeavyHover: base.accent?.palette?.vivid[80] || base.gray[100],
    textAccentHeavyPressed: base.accent?.palette?.dim[64] || base.gray[100],
    textErrorHeavy: base.customizable.red.vivid[68],
    textErrorHeavyHover: base.customizable.red.vivid[72],
    textErrorHeavyPressed: base.customizable.red.dim[64],
    textInvertedAccentHeavy: base.accent?.palette?.vivid[52] || base.blackAlpha[88],
    textInvertedAccentHeavyHover: base.accent?.palette?.vivid[60] || base.blackAlpha[96],
    textInvertedAccentHeavyPressed: base.accent?.palette?.dim[48] || base.blackAlpha[96],
    textInvertedErrorHeavy: base.customizable.red.vivid[52],
    textInvertedErrorHeavyHover: base.customizable.red.vivid[60],
    textInvertedErrorHeavyPressed: base.customizable.red.dim[48],
    textInvertedNeutralFaint: base.blackAlpha[32],
    textInvertedNeutralHeavy: base.blackAlpha[88],
    textInvertedNeutralPale: base.blackAlpha[40],
    textInvertedNeutralSoft: base.blackAlpha[56],
    textInvertedSuccessHeavy: base.customizable.green.vivid[52],
    textInvertedSuccessHeavyHover: base.customizable.green.vivid[60],
    textInvertedSuccessHeavyPressed: base.customizable.green.dim[48],
    textInvertedWarningHeavy: base.warning.vivid[64],
    textInvertedWarningHeavyHover: base.warning.vivid[72],
    textInvertedWarningHeavyPressed: base.warning.dim[56],
    textLogo: base.brand.logo.dark,
    textNeutralFaint: base.whiteAlpha[40],
    textNeutralHeavy: base.whiteAlpha[96],
    textNeutralPale: base.whiteAlpha[48],
    textNeutralSoft: base.whiteAlpha[64],
    textSuccessHeavy: base.customizable.green.vivid[72],
    textSuccessHeavyHover: base.customizable.green.vivid[80],
    textSuccessHeavyPressed: base.customizable.green.dim[64],
    textWarningHeavy: base.warning.vivid[80],
    textWarningHeavyHover: base.warning.vivid[84],
    textWarningHeavyPressed: base.warning.dim[72],
    textConstFaintBlack: base.blackAlpha[32],
    textConstFaintWhite: base.whiteAlpha[40],
    textConstHeavyBlack: base.blackAlpha[88],
    textConstHeavyWhite: base.whiteAlpha[96],
    textConstPaleBlack: base.blackAlpha[40],
    textConstPaleWhite: base.whiteAlpha[48],
    textConstSoftBlack: base.blackAlpha[56],
    textConstSoftWhite: base.whiteAlpha[64],
    textOnAccentBoldFaint: base.onAccent?.[32] || base.blackAlpha[32],
    textOnAccentBoldHeavy: base.onAccent?.[96] || base.blackAlpha[88],
    textOnAccentBoldPale: base.onAccent?.[40] || base.blackAlpha[40],
    textOnAccentBoldSoft: base.onAccent?.[56] || base.blackAlpha[56],
    textOnBrandOriginalFaint: base.onBrand[40],
    textOnBrandOriginalHeavy: base.onBrand[96],
    textOnBrandOriginalPale: base.onBrand[48],
    textOnBrandOriginalSoft: base.onBrand[64],
    shapeBoldAccent: base.accent?.original.dark || base.gray[96],
    shapeBoldAccentHover: base.accent?.interactions.hover.dark || base.gray[100],
    shapeBoldAccentPressed: base.accent?.interactions.pressed.dark || base.gray[84],
    shapeBoldBrandOriginal: base.brand.original,
    shapeBoldBrandOriginalHover: base.brand.interactions.hover.dark,
    shapeBoldBrandOriginalPressed: base.brand.interactions.pressed.light,
    shapeBoldError: base.customizable.red.normal[60],
    shapeBoldErrorHover: base.customizable.red.normal[64],
    shapeBoldErrorPressed: base.customizable.red.dim[52],
    shapeBoldNeutral: base.gray[80],
    shapeBoldNeutralHover: base.gray[88],
    shapeBoldNeutralPressed: base.whiteAlpha[56],
    shapeBoldSuccess: base.customizable.green.normal[60],
    shapeBoldSuccessHover: base.customizable.green.normal[64],
    shapeBoldSuccessPressed: base.customizable.green.dim[52],
    shapeBoldWarning: base.warning.normal[80],
    shapeBoldWarningHover: base.warning.normal[84],
    shapeBoldWarningPressed: base.warning.dim[72],
    shapeFaintAccent: base.accent?.palette?.dim[32] || base.whiteAlpha[12],
    shapeFaintAccentHover: base.accent?.palette?.dim[36] || base.whiteAlpha[16],
    shapeFaintAccentPressed: base.accent?.palette?.dim[28] || base.whiteAlpha[8],
    shapeFaintBrand: base.brand.palette?.dim[32],
    shapeFaintBrandHover: base.brand.palette?.dim[36],
    shapeFaintBrandPressed: base.brand.palette?.dim[28],
    shapeFaintError: base.customizable.red.dim[32],
    shapeFaintErrorHover: base.customizable.red.dim[36],
    shapeFaintErrorPressed: base.customizable.red.dim[28],
    shapeFaintNeutralAlpha: base.whiteAlpha[6],
    shapeFaintNeutralAlphaHover: base.whiteAlpha[8],
    shapeFaintNeutralAlphaPressed: base.whiteAlpha[4],
    shapeFaintSuccess: base.customizable.green.dim[32],
    shapeFaintSuccessHover: base.customizable.green.dim[36],
    shapeFaintSuccessPressed: base.customizable.green.dim[28],
    shapeFaintWarning: base.warning.dim[32],
    shapeFaintWarningHover: base.warning.dim[36],
    shapeFaintWarningPressed: base.warning.dim[28],
    shapeHeavyError: base.customizable.red.vivid[92],
    shapeHeavyNeutral: base.gray[96],
    shapeHeavySuccess: base.customizable.green.normal[92],
    shapeHeavyWarning: base.warning.vivid[92],
    shapeOtherAccentBoldDisabled: base.whiteAlpha[32],
    shapeOtherBacklessHover: base.whiteAlpha[6],
    shapeOtherBacklessPressed: base.whiteAlpha[4],
    shapeOtherBase: base.whiteAlpha[6],
    shapeOtherBaseHover: base.whiteAlpha[8],
    shapeOtherBasePressed: base.whiteAlpha[4],
    shapeOtherDisabled: base.whiteAlpha[6],
    shapeOtherField: base.blackAlpha[16],
    shapeOtherFieldHover: base.blackAlpha[4],
    shapeOtherFieldPressed: base.blackAlpha[12],
    shapeOtherLow: base.blackAlpha[24],
    shapeOtherLowHover: base.blackAlpha[16],
    shapeOtherLowPressed: base.blackAlpha[32],
    shapeOtherNeutralFaintSolid: base.gray[32],
    shapeOtherNeutralFaintSolidHover: base.gray[36],
    shapeOtherNeutralFaintSolidPressed: base.gray[32],
    shapeOtherNeutralPaleSolid: base.gray[36],
    shapeOtherNeutralPaleSolidHover: base.gray[40],
    shapeOtherNeutralPaleSolidPressed: base.gray[32],
    shapeOtherNeutralSoftSolid: base.gray[40],
    shapeOtherNeutralSoftSolidHover: base.gray[48],
    shapeOtherNeutralSoftSolidPressed: base.gray[36],
    shapePaleAccent: base.accent?.palette?.dim[36] || base.whiteAlpha[16],
    shapePaleAccentHover: base.accent?.palette?.dim[40] || base.whiteAlpha[24],
    shapePaleAccentPressed: base.accent?.palette?.dim[32] || base.whiteAlpha[12],
    shapePaleBrand: base.brand.palette?.dim[36],
    shapePaleBrandHover: base.brand.palette?.dim[40],
    shapePaleBrandPressed: base.brand.palette?.dim[32],
    shapePaleError: base.customizable.red.dim[36],
    shapePaleErrorHover: base.customizable.red.dim[40],
    shapePaleErrorPressed: base.customizable.red.dim[32],
    shapePaleNeutralAlpha: base.whiteAlpha[12],
    shapePaleNeutralAlphaHover: base.whiteAlpha[16],
    shapePaleNeutralAlphaPressed: base.whiteAlpha[6],
    shapePaleSuccess: base.customizable.green.dim[36],
    shapePaleSuccessHover: base.customizable.green.dim[40],
    shapePaleSuccessPressed: base.customizable.green.dim[32],
    shapePaleWarning: base.warning.dim[36],
    shapePaleWarningHover: base.warning.dim[40],
    shapePaleWarningPressed: base.warning.dim[32],
    shapeSoftAccent: base.accent?.palette?.dim[48] || base.whiteAlpha[32],
    shapeSoftAccentHover: base.accent?.palette?.dim[52] || base.whiteAlpha[40],
    shapeSoftAccentPressed: base.accent?.palette?.dim[44] || base.whiteAlpha[24],
    shapeSoftBrand: base.brand.palette?.dim[48],
    shapeSoftBrandHover: base.brand.palette?.dim[52],
    shapeSoftBrandPressed: base.brand.palette?.dim[44],
    shapeSoftError: base.customizable.red.dim[48],
    shapeSoftErrorHover: base.customizable.red.dim[52],
    shapeSoftErrorPressed: base.customizable.red.dim[44],
    shapeSoftNeutralAlpha: base.whiteAlpha[16],
    shapeSoftNeutralAlphaHover: base.whiteAlpha[24],
    shapeSoftNeutralAlphaPressed: base.whiteAlpha[8],
    shapeSoftSuccess: base.customizable.green.dim[48],
    shapeSoftSuccessHover: base.customizable.green.dim[52],
    shapeSoftSuccessPressed: base.customizable.green.dim[44],
    shapeSoftWarning: base.warning.dim[52],
    shapeSoftWarningHover: base.warning.dim[56],
    shapeSoftWarningPressed: base.warning.dim[48],
    shapeInvertedBacklessHover: base.blackAlpha[6],
    shapeInvertedBacklessPressed: base.blackAlpha[16],
    shapeInvertedDisabled: base.blackAlpha[6],
    shapeInvertedNeutralFaintAlpha: base.blackAlpha[6],
    shapeInvertedNeutralFaintAlphaHover: base.blackAlpha[12],
    shapeInvertedNeutralFaintAlphaPressed: base.blackAlpha[16],
    shapeInvertedNeutralHeavy: base.blackAlpha[80],
    shapeInvertedNeutralHeavyHover: base.blackAlpha[88],
    shapeInvertedNeutralHeavyPressed: base.blackAlpha[72],
    shapeInvertedNeutralPaleAlpha: base.blackAlpha[12],
    shapeInvertedNeutralPaleAlphaHover: base.blackAlpha[16],
    shapeInvertedNeutralPaleAlphaPressed: base.blackAlpha[24],
    shapeInvertedNeutralSoftAlpha: base.blackAlpha[16],
    shapeInvertedNeutralSoftAlphaHover: base.blackAlpha[24],
    shapeInvertedNeutralSoftAlphaPressed: base.blackAlpha[32],
    shapeConstBacklessBlackHover: base.blackAlpha[12],
    shapeConstBacklessBlackPressed: base.blackAlpha[16],
    shapeConstBacklessWhiteHover: base.whiteAlpha[12],
    shapeConstBacklessWhitePressed: base.whiteAlpha[6],
    shapeConstDisabledBlack: base.blackAlpha[6],
    shapeConstDisabledWhite: base.whiteAlpha[6],
    shapeConstFaintBlack: base.blackAlpha[12],
    shapeConstFaintBlackHover: base.blackAlpha[16],
    shapeConstFaintBlackPressed: base.blackAlpha[24],
    shapeConstFaintWhite: base.whiteAlpha[12],
    shapeConstFaintWhiteHover: base.whiteAlpha[16],
    shapeConstFaintWhitePressed: base.whiteAlpha[8],
    shapeConstHeavyBlack: base.blackAlpha[80],
    shapeConstHeavyBlackHover: base.blackAlpha[88],
    shapeConstHeavyBlackPressed: base.blackAlpha[64],
    shapeConstHeavyWhite: base.whiteAlpha[96],
    shapeConstHeavyWhiteHover: base.gray[100],
    shapeConstHeavyWhitePressed: base.whiteAlpha[64],
    shapeConstPaleBlack: base.blackAlpha[16],
    shapeConstPaleBlackHover: base.blackAlpha[24],
    shapeConstPaleBlackPressed: base.blackAlpha[32],
    shapeConstPaleWhite: base.whiteAlpha[16],
    shapeConstPaleWhiteHover: base.whiteAlpha[24],
    shapeConstPaleWhitePressed: base.whiteAlpha[12],
    shapeConstPromo: base.brand.promo,
    shapeConstSoftBlack: base.blackAlpha[24],
    shapeConstSoftBlackHover: base.blackAlpha[32],
    shapeConstSoftBlackPressed: base.blackAlpha[40],
    shapeConstSoftWhite: base.whiteAlpha[24],
    shapeConstSoftWhiteHover: base.whiteAlpha[32],
    shapeConstSoftWhitePressed: base.whiteAlpha[24],
    lineAccentBold: base.accent?.original.dark || base.gray[88],
    lineAccentBoldHover: base.accent?.interactions.hover.dark || base.gray[100],
    lineAccentBoldPressed: base.accent?.interactions.pressed.dark || base.whiteAlpha[64],
    lineAccentPale: base.accent?.palette?.dim[40] || base.whiteAlpha[24],
    lineAccentPaleHover: base.accent?.palette?.dim[44] || base.whiteAlpha[32],
    lineAccentPalePressed: base.accent?.palette?.dim[36] || base.whiteAlpha[16],
    lineAccentSoft: base.accent?.palette?.dim[48] || base.whiteAlpha[48],
    lineAccentSoftHover: base.accent?.palette?.vivid[80] || base.gray[100],
    lineAccentSoftPressed: base.accent?.palette?.dim[64] || base.gray[100],
    lineBrandOriginal: base.brand.original,
    lineErrorBold: base.customizable.red.vivid[60],
    lineErrorBoldHover: base.customizable.red.vivid[68],
    lineErrorBoldPressed: base.customizable.red.dim[56],
    lineNeutralFaint: base.whiteAlpha[8],
    lineNeutralPale: base.whiteAlpha[16],
    lineNeutralPaleHover: base.whiteAlpha[24],
    lineNeutralPalePressed: base.whiteAlpha[12],
    lineOnAccentBoldFaint: base.onAccent?.[12] || base.blackAlpha[12],
    lineOnAccentBoldPale: base.onAccent?.[24] || base.blackAlpha[24],
    lineOnBrandOriginalFaint: base.onBrand[12],
    lineOnBrandOriginalPale: base.onBrand[24],
    lineSuccessBold: base.customizable.green.vivid[60],
    lineSuccessBoldHover: base.customizable.green.vivid[68],
    lineSuccessBoldPressed: base.customizable.green.dim[56],
    lineWarningBold: base.warning.vivid[80],
    lineWarningBoldHover: base.warning.vivid[84],
    lineWarningBoldPressed: base.warning.dim[72],
    lineInvertedAccentBold: base.accent?.original.light || base.gray[44],
    lineInvertedAccentBoldHover: base.accent?.interactions.hover.light || base.gray[20],
    lineInvertedAccentBoldPressed: base.accent?.interactions.pressed.light || base.blackAlpha[64],
    lineInvertedAccentPale: base.accent?.palette?.normal[84] || base.blackAlpha[24],
    lineInvertedAccentPaleHover: base.accent?.palette?.normal[80] || base.blackAlpha[32],
    lineInvertedAccentPalePressed: base.accent?.palette?.dim[76] || base.blackAlpha[40],
    lineInvertedAccentSoft: base.accent?.palette?.dim[76] || base.blackAlpha[48],
    lineInvertedAccentSoftHover: base.accent?.palette?.vivid[60] || base.blackAlpha[96],
    lineInvertedAccentSoftPressed: base.accent?.palette?.dim[48] || base.blackAlpha[96],
    lineInvertedErrorBold: base.customizable.red.vivid[56],
    lineInvertedErrorBoldHover: base.customizable.red.vivid[64],
    lineInvertedErrorBoldPressed: base.customizable.red.dim[52],
    lineInvertedNeutralFaint: base.blackAlpha[8],
    lineInvertedNeutralPale: base.blackAlpha[16],
    lineInvertedNeutralPaleHover: base.blackAlpha[24],
    lineInvertedNeutralPalePressed: base.blackAlpha[32],
    lineInvertedSuccessBold: base.customizable.green.vivid[56],
    lineInvertedSuccessBoldHover: base.customizable.green.vivid[68],
    lineInvertedSuccessBoldPressed: base.customizable.green.dim[56],
    lineInvertedWarningBold: base.warning.vivid[80],
    lineInvertedWarningBoldHover: base.warning.vivid[72],
    lineInvertedWarningBoldPressed: base.warning.dim[68],
    lineConstFaintBlack: base.blackAlpha[12],
    lineConstFaintWhite: base.whiteAlpha[12],
    lineConstPaleBlack: base.blackAlpha[24],
    lineConstPaleBlackHover: base.blackAlpha[32],
    lineConstPaleBlackPressed: base.blackAlpha[16],
    lineConstPaleWhite: base.whiteAlpha[24],
    lineConstPaleWhiteHover: base.whiteAlpha[32],
    lineConstPaleWhitePressed: base.whiteAlpha[16],
    surfaceBase: base.gray[28],
    surfaceHigh: base.gray[32],
    surfaceLow: base.gray[24],
    surfaceModalBackdrop: base.blackAlpha[40],
    illustrationBlack: base.gray[16],
    illustrationBrand: base.brand.original,
    illustrationComplement: base.gray[100],
    illustrationInvertedNeutral: base.gray[0],
    illustrationNeutral: base.gray[100],
    illustrationOnBrand: base.onBrand[100],
    illustrationOnComplement: base.brand.promo,
    illustrationPromo: base.brand.promo,
    illustrationSymbol: base.brand.palette?.normal[80],
    illustrationWhite: base.gray[100],
    customizableBoldBlack: base.gray[76],
    customizableBoldBlue: base.customizable.blue.normal[64],
    customizableBoldBlueDeep: base.customizable.blueDeep.vivid[60],
    customizableBoldGray: base.gray[52],
    customizableBoldGreen: base.customizable.green.normal[64],
    customizableBoldMint: base.customizable.mint.normal[68],
    customizableBoldOrange: base.customizable.orange.normal[68],
    customizableBoldPurple: base.customizable.purple.normal[64],
    customizableBoldRed: base.customizable.red.normal[64],
    customizableBoldViolet: base.customizable.violet.normal[64],
    customizableBoldYellow: base.customizable.yellow.vivid[76],
    customizableFaintBlack: base.gray[40],
    customizableFaintBlue: base.customizable.blue.dim[32],
    customizableFaintBlueDeep: base.customizable.blueDeep.dim[32],
    customizableFaintGray: base.gray[32],
    customizableFaintGreen: base.customizable.green.dim[32],
    customizableFaintMint: base.customizable.mint.dim[32],
    customizableFaintOrange: base.customizable.orange.dim[32],
    customizableFaintPurple: base.customizable.purple.dim[32],
    customizableFaintRed: base.customizable.red.dim[32],
    customizableFaintViolet: base.customizable.violet.dim[32],
    customizableFaintYellow: base.customizable.yellow.dim[32],
    customizableHeavyBlack: base.gray[96],
    customizableHeavyBlue: base.customizable.blue.vivid[80],
    customizableHeavyBlueDeep: base.customizable.blueDeep.vivid[76],
    customizableHeavyGray: base.gray[60],
    customizableHeavyGreen: base.customizable.green.vivid[84],
    customizableHeavyMint: base.customizable.mint.vivid[88],
    customizableHeavyOrange: base.customizable.orange.vivid[76],
    customizableHeavyPurple: base.customizable.purple.vivid[80],
    customizableHeavyRed: base.customizable.red.vivid[76],
    customizableHeavyViolet: base.customizable.violet.vivid[76],
    customizableHeavyYellow: base.customizable.yellow.vivid[84],
    customizablePaleBlack: base.gray[44],
    customizablePaleBlue: base.customizable.blue.dim[36],
    customizablePaleBlueDeep: base.customizable.blueDeep.dim[36],
    customizablePaleGray: base.gray[36],
    customizablePaleGreen: base.customizable.green.dim[36],
    customizablePaleMint: base.customizable.mint.dim[36],
    customizablePaleOrange: base.customizable.orange.dim[36],
    customizablePalePurple: base.customizable.purple.dim[36],
    customizablePaleRed: base.customizable.red.dim[36],
    customizablePaleViolet: base.customizable.violet.dim[36],
    customizablePaleYellow: base.customizable.yellow.dim[36],
    customizableSoftBlack: base.gray[56],
    customizableSoftBlue: base.customizable.blue.dim[48],
    customizableSoftBlueDeep: base.customizable.blueDeep.dim[48],
    customizableSoftGray: base.gray[44],
    customizableSoftGreen: base.customizable.green.dim[48],
    customizableSoftMint: base.customizable.mint.dim[48],
    customizableSoftOrange: base.customizable.orange.dim[48],
    customizableSoftPurple: base.customizable.purple.dim[48],
    customizableSoftRed: base.customizable.red.dim[48],
    customizableSoftViolet: base.customizable.violet.dim[48],
    customizableSoftYellow: base.customizable.yellow.dim[52],
  },
});
