package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    expectBuildTypesOrder(RelativeId("RunAll"), RelativeId("LintAndTest"), RelativeId("LintTestReactUiValidations"), RelativeId("SeleniumTesting"), RelativeId("TestUi"), RelativeId("Build"), RelativeId("BuildReactUiValidations"), RelativeId("PublishRetailUi"), RelativeId("PublishReactUiValidations"), RelativeId("PublishReactUiTesting"))
    buildTypesOrderIds = arrayListOf(RelativeId("RunAll"), RelativeId("LintAndTest"), RelativeId("LintTestReactUiValidations"), RelativeId("SeleniumTesting"), RelativeId("TestUi"), RelativeId("Build"), RelativeId("BuildReactUiValidations"), RelativeId("PublishRetailUi"), RelativeId("PublishReactUiValidations"), RelativeId("PublishReactUiTesting"), RelativeId("CandyEngineScreenshotTests"))
}
