package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    cleanup {
        expect {
            all(days = 30)
        }
        update {
            all(days = 60)
        }
        add {
            history(days = 60)
        }
        add {
            artifacts(days = 30)
        }
    }
}
