package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with absolute id = 'Common_ReactSorge'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id = AbsoluteId("Common_ReactSorge")
    name = "React Sorge"

    features {
        githubConnection {
            id = "PROJECT_EXT_197"
            displayName = "GitHub.com"
            clientId = "react-ui"
            clientSecret = "credentialsJSON:6779190e-67a7-4aba-bfa5-8d48b8c56ebb"
        }
    }
}))

