package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Validations'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Validations")) {
    expectBuildTypesOrder(RelativeId("Validations_LintTest"), RelativeId("Validations_Build"), RelativeId("Validations_Publish"), RelativeId("Validations_ScreenshotTests"))
    buildTypesOrderIds = arrayListOf(RelativeId("Validations_LintTest"), RelativeId("Validations_Build"), RelativeId("Validations_Publish"), RelativeId("Validations_ScreenshotTests"), RelativeId("Validations_Storybook"))
}
