package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with absolute id = 'Common_ReactSorge_HttpsGithubComSkbkonturReactSorgeGitRefsHeadsMaster'
in the project with absolute id = 'Common_ReactSorge', and delete the patch script.
*/
create(AbsoluteId("Common_ReactSorge"), GitVcsRoot({
    id = AbsoluteId("Common_ReactSorge_HttpsGithubComSkbkonturReactSorgeGitRefsHeadsMaster")
    name = "https://github.com/skbkontur/react-sorge.git"
    url = "https://github.com/skbkontur/react-sorge.git"
    branchSpec = "+:*"
}))

