package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'KeformsEngine'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("KeformsEngine")
    name = "keforms.engine"
    url = "git@git.skbkontur.ru:ke/keforms-engine.git"
    branchSpec = "+:refs/heads/*"
    userNameStyle = GitVcsRoot.UserNameStyle.FULL
    agentGitPath = """C:\Program Files\Git\bin\git.exe"""
    authMethod = defaultPrivateKey {
        userName = "git"
    }
}))

