package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'RetailUiSettings'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("RetailUiSettings")
    name = "retail-ui settings"
    url = "https://github.com/skbkontur/retail-ui.git"
    branch = "refs/heads/teamcity-settings"
    branchSpec = """
        +:refs/heads/*
        +:refs/tags/*
    """.trimIndent()
    useTagsAsBranches = true
    authMethod = password {
        userName = "skbkontur-bot"
        password = "credentialsJSON:8159ccad-3d3e-43fa-9684-5cd8d9e83d0e"
    }
}))

