package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'RetailUi'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("RetailUi")) {
    val expected = GitVcsRoot({
        id("RetailUi")
        name = "retail-ui"
        url = "https://github.com/skbkontur/retail-ui.git"
        branchSpec = """
            +:refs/heads/*
            +:refs/tags/*
        """.trimIndent()
        useTagsAsBranches = true
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "skbkontur-bot"
            password = "credentialsJSON:8159ccad-3d3e-43fa-9684-5cd8d9e83d0e"
        }
    }

}
