matrix-tests:
  stage: diff.versions.testing
  parallel:
    matrix:
      - REACT_VERSION: [ "17", "18" ]
        TYPESCRIPT_VERSION: [ "4", "5" ]
        STRICT_MODE: [ "true", "false" ]
  when: manual
  trigger:
    strategy: depend
    include:
      - local: /.gitlab-ci/stages/tests.yml
