.cache_common: &cache_common
  key:
    files:
      - yarn.lock
  paths:
    - '**/node_modules/'

.cache_push:
  cache:
    <<: *cache_common
    policy: push

.use_install_cache:
  cache:
    <<: *cache_common
    policy: pull

yarn_install:
  image: docker-proxy.kontur.host/node:18-alpine
  extends:
    - .cache_push
  stage: .pre
  script:
    - source .gitlab-ci/scripts/install/install.sh
