include:
  - '/.gitlab-ci/templates/base.yml'
  - '/.gitlab-ci/stages/install.yml'

React-UI · Lint/Tests:
  stage: test
  extends:
    - .test-base
    - .react-ui-workspace
    - .use_install_cache
  script:
    - source .gitlab-ci/scripts/tests/lint.sh $WORKSPACE
    - source .gitlab-ci/scripts/tests/unit.sh $WORKSPACE

React-UI · Smoke Tests:
  extends:
    - .test-base
    - .install-browser-utilities
    - .react-ui-smoke-test-workspace
  stage: test
  script:
    # доставить браузер в root https://forum.gitlab.com/t/artifacts-outside-the-project-directory/68214 поэтому тут отдельный свой install
    # плюс для версионного тестирования нужно патчить файлы в этом проетке
    - source .gitlab-ci/scripts/install/install.sh
    - source .gitlab-ci/scripts/tests/smoke.sh $WORKSPACE

React-UI · Screenshot tests:
  extends:
    - .install-ip-utilities
    - .test-base
    - .react-ui-workspace
    - .use_install_cache
  stage: test
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/packages/react-ui/reports/*
  script:
    - source .gitlab-ci/scripts/storybook/build.sh $WORKSPACE
    - source .gitlab-ci/scripts/creevey/test.sh $WORKSPACE "react-ui"

React-UI · Build:
  extends:
    - .test-base
    - .react-ui-workspace
    - .use_install_cache
  stage: test
  variables:
    FILENAME: "skbkontur-react-ui.tgz"
  artifacts:
    paths:
      - $CI_PROJECT_DIR/packages/react-ui/$FILENAME
  script:
    - source .gitlab-ci/scripts/build/build.sh $WORKSPACE
    - source .gitlab-ci/scripts/build/pack.sh $WORKSPACE $FILENAME

Validations · Lint/Tests:
  extends:
    - .test-base
    - .react-ui-validations-workspace
    - .use_install_cache
  stage: test
  script:
    - source .gitlab-ci/scripts/tests/lint.sh $WORKSPACE
    - source .gitlab-ci/scripts/tests/unit.sh $WORKSPACE

Validations · Build:
  extends:
    - .test-base
    - .react-ui-validations-workspace
    - .use_install_cache
  stage: test
  variables:
    FILENAME: "skbkontur-react-ui-validations.tgz"
  artifacts:
    paths:
      - $CI_PROJECT_DIR/packages/react-ui-validations/build
  script:
    - source .gitlab-ci/scripts/build/build.sh $WORKSPACE
    - source .gitlab-ci/scripts/publish/predeploy.sh $WORKSPACE
    - source .gitlab-ci/scripts/build/pack.sh $WORKSPACE $FILENAME

Selenium Testing:
  extends:
    - .test-base
    - .react-ui-validations-workspace
  stage: test
  when: manual
  script:
    - echo "что-то с дотнетом, позже разберусь"

Validations · Screenshot tests:
  extends:
    - .install-ip-utilities
    - .test-base
    - .react-ui-validations-workspace
    - .use_install_cache
  stage: test
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/packages/react-ui-validations/reports/*
  script:
    - source .gitlab-ci/scripts/storybook/build.sh $WORKSPACE
    - source .gitlab-ci/scripts/creevey/test.sh $WORKSPACE "react-ui-validations"

Validations · NUnit:
  extends:
    - .test-base
    - .react-ui-validations-workspace
  stage: test
  when: manual
  script:
    - echo "что-то с дотнетом, позже разберусь"
