import { useState } from "react";
import Head from "next/head";
import { Button } from "@skbkontur/react-ui/components/Button";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const [counter, setCounter] = useState(0);

  return (
    <>
      <Head>
        <title>Kontur UI Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.App}`}>
        <Button size="medium" onClick={() => setCounter(counter - 1)}>
          −
        </Button>
        <div className={`${styles.App_counter}`}>{counter}</div>
        <Button size="medium" onClick={() => setCounter(counter + 1)}>
          +
        </Button>
      </div>
    </>
  );
}
