export const initialData = [
  {
    id: 1,
    client: 'ООО «Кавычки»',
    region: 'Курская обл 46',
    amount: 85000,
    responsible: { name: 'Антон Чехов' },
  },
  {
    id: 2,
    client: 'Рыков Н. В.',
    region: 'Хакасия 19',
    amount: 127000,
    responsible: { name: 'Алексей Толстой' },
  },
  {
    id: 3,
    client: 'ООО «Альянс Авиа»',
    region: 'Свердловская об...',
    amount: 5000,
    responsible: { name: 'Иван Тургенев' },
  },
  {
    id: 4,
    client: 'ЗАО "Восход"',
    region: 'Московская обл 50',
    amount: 90000,
    responsible: { name: 'Мария Смирнова' },
  },
  {
    id: 5,
    client: 'ИП Петров',
    region: 'Санкт-Петербург 78',
    amount: 30000,
    responsible: { name: 'Дмитрий Иванов' },
  },
  {
    id: 6,
    client: 'ООО «Аврора»',
    region: 'Курская обл 46',
    amount: 45000,
    responsible: { name: 'Анна Васильева' },
  },
  {
    id: 7,
    client: 'ЗАО «Конфета+»',
    region: 'Белгородская обл 31',
    amount: 72000,
    responsible: { name: 'Сергей Николаев' },
  },
  {
    id: 8,
    client: 'ООО «Грин Лайн»',
    region: 'Краснодарский кр 23',
    amount: 110000,
    responsible: { name: 'Ольга Кузнецова' },
  },
  {
    id: 9,
    client: 'ООО «Техносфера»',
    region: 'Ростовская обл 61',
    amount: 95000,
    responsible: { name: 'Павел Захаров' },
  },
  {
    id: 10,
    client: 'ЗАО «Бизнес-Импульс»',
    region: 'Воронежская обл 36',
    amount: 60000,
    responsible: { name: 'Елена Федорова' },
  },
  {
    id: 11,
    client: 'ООО «Мегаполис»',
    region: 'Нижегородская обл 52',
    amount: 140000,
    responsible: { name: 'Игорь Морозов' },
  },
  {
    id: 12,
    client: 'ООО «Инфоматика»',
    region: 'Самарская обл 63',
    amount: 88000,
    responsible: { name: 'Светлана Новикова' },
  },
  {
    id: 13,
    client: 'АО «Премьер»',
    region: 'Татарстан 16',
    amount: 55000,
    responsible: { name: 'Виктор Козлов' },
  },
  {
    id: 14,
    client: 'ООО «Экопродукт»',
    region: 'Челябинская обл 74',
    amount: 105000,
    responsible: { name: 'Наталья Орлова' },
  },
  {
    id: 15,
    client: 'ООО «БиоХимСервис»',
    region: 'Пермский кр 59',
    amount: 132000,
    responsible: { name: 'Денис Волков' },
  },
  {
    id: 16,
    client: 'ООО «Норд-Стрим»',
    region: 'Архангельская обл 29',
    amount: 78000,
    responsible: { name: 'Юлия Соколова' },
  },
  {
    id: 17,
    client: 'ООО «Сфера Логистики»',
    region: 'Новосибирская обл 54',
    amount: 99000,
    responsible: { name: 'Андрей Павлов' },
  },
  {
    id: 18,
    client: 'ЗАО «НЭВЗ»',
    region: 'Иркутская обл 38',
    amount: 68000,
    responsible: { name: 'Анастасия Морозова' },
  },
  {
    id: 19,
    client: 'ООО «Лазурит»',
    region: 'Волгоградская обл 34',
    amount: 115000,
    responsible: { name: 'Егор Ковалев' },
  },
  {
    id: 20,
    client: 'ЗАО «НеоТех»',
    region: 'Калининградская обл 39',
    amount: 82000,
    responsible: { name: 'Полина Егорова' },
  },
];
