// flow-typed signature: 83ac7d33443e022537474e5d459aab48
// flow-typed version: <<STUB>>/@kadira/storybook-addons_v1.6.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-addons/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook-addons/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-addons/dist/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addons/dist/index'>;
}
declare module '@kadira/storybook-addons/src/index.js' {
  declare module.exports: $Exports<'@kadira/storybook-addons/src/index'>;
}
