package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.failureConditions.BuildFailureOnMetric
import jetbrains.buildServer.configs.kotlin.v2018_2.failureConditions.failOnMetricChange
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'ReactUI_GitHubFeatures'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("ReactUI_GitHubFeatures")) {
    failureConditions {
        add {
            failOnMetricChange {
                id = "BUILD_EXT_320"
                metric = BuildFailureOnMetric.MetricType.BUILD_DURATION
                threshold = 3600
                units = BuildFailureOnMetric.MetricUnit.DEFAULT_UNIT
                comparison = BuildFailureOnMetric.MetricComparison.MORE
                compareTo = value()
                stopBuildOnFailure = true
            }
        }
    }
}
