package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'ReactUI_GitHubFeatures'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("ReactUI_GitHubFeatures")) {
    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                id = "PULL_REQUESTS"
                provider = github {
                    serverUrl = ""
                    authType = token {
                        token = "credentialsJSON:37119025-2749-4abf-8ed8-ff4221b59d50"
                    }
                    filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER_OR_COLLABORATOR
                }
            }
        }
        feature1.apply {
            provider = github {
                serverUrl = ""
                authType = token {
                    token = "credentialsJSON:7fd959b6-0b07-4bf1-87d0-1ce9c443528e"
                }
                filterSourceBranch = ""
                filterTargetBranch = ""
                filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER_OR_COLLABORATOR
            }
        }
        val feature2 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                id = "COMMIT_STATUS_PUBLISHER"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:753f3391-1e06-4223-8a34-70a7c9adb2af"
                    }
                }
            }
        }
        feature2.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:7fd959b6-0b07-4bf1-87d0-1ce9c443528e"
                }
            }
        }
    }
}
