package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Template
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2018_2.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'ReactUI_GitHubFeatures'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Template({
    id("ReactUI_GitHubFeatures")
    name = "GitHub Features"

    triggers {
        vcs {
            id = "TRIGGER_1"
            branchFilter = "+:pull/*"
        }
    }

    features {
        swabra {
            id = "BUILD_EXT_1"
            forceCleanCheckout = true
        }
        pullRequests {
            id = "BUILD_EXT_2"
            provider = github {
                authType = token {
                    token = "credentialsJSON:37119025-2749-4abf-8ed8-ff4221b59d50"
                }
                filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
            }
        }
        commitStatusPublisher {
            id = "BUILD_EXT_3"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = password {
                    userName = "skbkontur-bot"
                    password = "credentialsJSON:8159ccad-3d3e-43fa-9684-5cd8d9e83d0e"
                }
            }
        }
    }
}))

