// flow-typed signature: 9572e955b784eb3f2eea43b8ff2d1fa2
// flow-typed version: <<STUB>>/mockdate_v^2.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockdate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockdate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockdate/src/mockdate' {
  declare module.exports: any;
}

declare module 'mockdate/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockdate/src/mockdate.js' {
  declare module.exports: $Exports<'mockdate/src/mockdate'>;
}
declare module 'mockdate/test/index.js' {
  declare module.exports: $Exports<'mockdate/test/index'>;
}
