// flow-typed signature: 06812019bf21f23cc55905a35f56a68b
// flow-typed version: <<STUB>>/react-addons-css-transition-group_v0.14.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-css-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-css-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-addons-css-transition-group/index' {
  declare module.exports: $Exports<'react-addons-css-transition-group'>;
}
declare module 'react-addons-css-transition-group/index.js' {
  declare module.exports: $Exports<'react-addons-css-transition-group'>;
}
