// flow-typed signature: 84898c52e4a8ca72c75310b99be79eac
// flow-typed version: <<STUB>>/theming_v^1.3.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'theming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'theming/dist/cjs/channel' {
  declare module.exports: any;
}

declare module 'theming/dist/cjs/create-theme-listener' {
  declare module.exports: any;
}

declare module 'theming/dist/cjs/create-theme-provider' {
  declare module.exports: any;
}

declare module 'theming/dist/cjs/create-with-theme' {
  declare module.exports: any;
}

declare module 'theming/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'theming/dist/esm/channel' {
  declare module.exports: any;
}

declare module 'theming/dist/esm/create-theme-listener' {
  declare module.exports: any;
}

declare module 'theming/dist/esm/create-theme-provider' {
  declare module.exports: any;
}

declare module 'theming/dist/esm/create-with-theme' {
  declare module.exports: any;
}

declare module 'theming/dist/esm/index' {
  declare module.exports: any;
}

declare module 'theming/src/channel' {
  declare module.exports: any;
}

declare module 'theming/src/create-theme-listener' {
  declare module.exports: any;
}

declare module 'theming/src/create-theme-listener.test' {
  declare module.exports: any;
}

declare module 'theming/src/create-theme-provider' {
  declare module.exports: any;
}

declare module 'theming/src/create-theme-provider.test' {
  declare module.exports: any;
}

declare module 'theming/src/create-with-theme' {
  declare module.exports: any;
}

declare module 'theming/src/create-with-theme.test' {
  declare module.exports: any;
}

declare module 'theming/src/index' {
  declare module.exports: any;
}

declare module 'theming/src/index.test' {
  declare module.exports: any;
}

declare module 'theming/src/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'theming/dist/cjs/channel.js' {
  declare module.exports: $Exports<'theming/dist/cjs/channel'>;
}
declare module 'theming/dist/cjs/create-theme-listener.js' {
  declare module.exports: $Exports<'theming/dist/cjs/create-theme-listener'>;
}
declare module 'theming/dist/cjs/create-theme-provider.js' {
  declare module.exports: $Exports<'theming/dist/cjs/create-theme-provider'>;
}
declare module 'theming/dist/cjs/create-with-theme.js' {
  declare module.exports: $Exports<'theming/dist/cjs/create-with-theme'>;
}
declare module 'theming/dist/cjs/index.js' {
  declare module.exports: $Exports<'theming/dist/cjs/index'>;
}
declare module 'theming/dist/esm/channel.js' {
  declare module.exports: $Exports<'theming/dist/esm/channel'>;
}
declare module 'theming/dist/esm/create-theme-listener.js' {
  declare module.exports: $Exports<'theming/dist/esm/create-theme-listener'>;
}
declare module 'theming/dist/esm/create-theme-provider.js' {
  declare module.exports: $Exports<'theming/dist/esm/create-theme-provider'>;
}
declare module 'theming/dist/esm/create-with-theme.js' {
  declare module.exports: $Exports<'theming/dist/esm/create-with-theme'>;
}
declare module 'theming/dist/esm/index.js' {
  declare module.exports: $Exports<'theming/dist/esm/index'>;
}
declare module 'theming/src/channel.js' {
  declare module.exports: $Exports<'theming/src/channel'>;
}
declare module 'theming/src/create-theme-listener.js' {
  declare module.exports: $Exports<'theming/src/create-theme-listener'>;
}
declare module 'theming/src/create-theme-listener.test.js' {
  declare module.exports: $Exports<'theming/src/create-theme-listener.test'>;
}
declare module 'theming/src/create-theme-provider.js' {
  declare module.exports: $Exports<'theming/src/create-theme-provider'>;
}
declare module 'theming/src/create-theme-provider.test.js' {
  declare module.exports: $Exports<'theming/src/create-theme-provider.test'>;
}
declare module 'theming/src/create-with-theme.js' {
  declare module.exports: $Exports<'theming/src/create-with-theme'>;
}
declare module 'theming/src/create-with-theme.test.js' {
  declare module.exports: $Exports<'theming/src/create-with-theme.test'>;
}
declare module 'theming/src/index.js' {
  declare module.exports: $Exports<'theming/src/index'>;
}
declare module 'theming/src/index.test.js' {
  declare module.exports: $Exports<'theming/src/index.test'>;
}
declare module 'theming/src/test-helpers.js' {
  declare module.exports: $Exports<'theming/src/test-helpers'>;
}
