export const TableDataTids = {
  root: 'Table__root',
  header: 'Table__header',
  body: 'Table__body',
  footer: 'Table__footer',
  row: 'Table__row',
  cell: 'Table__cell',
  headerCell: 'Table__headerCell',
  checkboxCell: 'Table__checkboxCell',
  headerCheckboxCell: 'Table__headerCheckboxCell',
  filter: 'Table__filter',
  clickableHeader: 'Table__clickableHeader',
  filterItem: 'Table__filterItem',
  filterSearch: 'Table__filterSearch',
  dropdownFilter: 'Table__dropdownFilter',
  dropdownSortableFilter: 'Table__dropdownSortableFilter',
  sort: 'Table__sort',
  filterResultRow: 'Table__filterResultRow',
  filterResultCell: 'Table__filterResultCell',
  appliedFilterToken: 'Table__token',
  roundButton: 'Table__roundButton',
  roundButtonsWrapper: 'Table__roundButtonsWrapper',
  actionsDropdownItem: 'Table__actionsDropdownItem',
  popupActionBar: 'Table__popupActionBar',
  actionsKebabButton: 'Table__button-kebab',
} as const;
