name: React UI Release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['next']
jobs:
  Beta:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Release Beta
        run: yarn release:beta
